[build-system]
# Setuptools & wheel pinned for numpy compilation: https://github.com/numpy/numpy/issues/22135
requires = ["setuptools==59.2.0", "oldest-supported-numpy", "wheel==0.37.0"]
build-backend = "setuptools.build_meta"
